Optional combine_pdf + support yarn pnp
Studiosity/grover pull request #266
Opened 2024-11-06 00:36 UTC by le0pard

## Reason for this changes

Gem `combine_pdf` needed only for middleware and only for `front_cover` and/or `back_cover` functionality. This mean, that people which use grover directly by `display_url` or raw html need to have this gem as additional dependency. Problem, that `combine_pdf` contain as deps https://github.com/caiges/Ruby-RC4 , which is not supported any more (dead dependency).

![Screenshot 2024-11-06 at 02 25 37](https://github.com/user-attachments/assets/6eafd66a-5293-44a5-a641-ff5b8bdb6237)

By this proposal I making `combine_pdf` as optional and not install as dependency, so developers, which need middleware and `front_cover` and/or `back_cover` functionality can install it separately in application.

Also added ability to override js runtime bin, so in this case devs, which use non standard env, like yarn pnp, can override hardcoded `node` bin (example added in README)

2024-11-17 23:48 UTC, abrom requested changes
Nice one @le0pard 👍 

I've got a few suggestions on some copy improvements, but otherwise looking solid

2024-11-17 23:48 UTC, abrom commented on README.md
> +If you ar using yarn pnp strategy, you can override how to run js runtime for grover:
```suggestion
If you are using the Yarn PnP strategy, you can override the run JS runtime for grover:
```

2024-11-17 23:48 UTC, abrom commented on lib/grover/middleware.rb
> +        raise Grover::Error, "You need install combine_pdf gem"
```suggestion
        raise Grover::Error, 'Please add/install the "combine_pdf" gem to use the front/back cover page feature'
```

2024-11-17 23:48 UTC, abrom commented on README.md
> +To use this functionality you need add [combine_pdf](https://rubygems.org/gems/combine_pdf) gem in your app.
```suggestion
Note, to use this functionality you need to add the [combine_pdf](https://rubygems.org/gems/combine_pdf) gem to your app.
```

Also, I think this paragraph should be moved down one (just below the "You can specify relative paths to the cover page contents using..." one).

2024-11-17 23:48 UTC, abrom commented on README.md
> +#### Yarn pnp strategy
```suggestion
#### Yarn PnP strategy
```

2024-11-18 09:03 UTC, le0pard commented
Thanks @abrom , fixed

2024-11-19 03:20 UTC, abrom approved these changes
Fantastic, thanks @le0pard 👍

2024-11-19 03:45 UTC, merged

2024-11-19 04:06 UTC, abrom commented
Released in [v1.2.0](https://rubygems.org/gems/grover/versions/1.2.0)