Add Ruby 3.4 support
Studiosity/grover pull request #275
Opened 2024-12-30 13:56 UTC by murajun1978

Support Ruby 3.4

Fixed #273

2025-01-01 17:15 UTC, Laykou commented
@abrom Could this be merged and released in rubygems please? Thank you!

2025-01-03 21:49 UTC, jibiel commented on grover.gemspec
> +  spec.required_ruby_version = ['>= 3.0.0', '< 3.5.0']
@abrom Any particular reason to lock Ruby version so tightly in this gem?

It'll be the same problem a few months later when 3.5 is released.
The gem prevents apps using it from upgrading Ruby.

2025-01-04 19:28 UTC, pboling commented on grover.gemspec
> +  spec.required_ruby_version = ['>= 3.0.0', '< 3.5.0']
I agree, it is not a reasonable restriction, except in the school of enterprisey business decisions.  Please relegate it to the foibles of the Ruby ecosystem's past!
This is blocking upgrades for me, so I may switch to sourcing from a git fork.

2025-01-05 13:43 UTC, erichstark commented
Any updates on this?

2025-01-05 17:44 UTC, pboling requested changes
Do not restrict to less than ruby 3.5 unless you want this gem to once again be a major upgrade blocker in 11 months.

2025-01-13 11:27 UTC, abrom commented on grover.gemspec
> +  spec.required_ruby_version = ['>= 3.0.0', '< 3.5.0']
> @abrom Any particular reason to lock Ruby version so tightly in this gem?
> 
> It'll be the same problem a few months later when 3.5 is released. The gem prevents apps using it from upgrading Ruby.

Because it hasn't been tested

2025-01-13 11:31 UTC, abrom commented on grover.gemspec
> +  spec.required_ruby_version = ['>= 3.0.0', '< 3.5.0']
> I agree, it is not a reasonable restriction, except in the school of enterprisey business decisions. Please relegate it to the foibles of the Ruby ecosystem's past! This is blocking upgrades for me, so I may switch to sourcing from a git fork.

Not reasonable to you, but expected by anyone who needs gems to work with the versions they're indicated as being supported by. 

I agree that it is a blocker, no doubt about it. The Ruby versions releasing over what is traditionally a holiday for many, including myself, shouldn't dictate the entire community drop everything to support a pretty extreme minority who need instant version bumps 😉 . If you absolutely need to be using the latest Ruby as soon as it's released is going to result in the need, as you've suggested, for using forks.. that's a given.

2025-01-13 11:43 UTC, abrom commented
> Do not restrict to less than ruby 3.5 unless you want this gem to once again be a major upgrade blocker in 11 months.

You want the gem to support a yet to be released version of the language ? In all likelihood it would work.. yes.. probably. But sorry, I'm not going to open the release versions up for a probably. Each release runs through a CI suite to ensure the gem is going to behave *exactly* how it is supposed to. How would that work for a yet to be released language? I can assure you that the vitriol I would receive because the gem SAID it supports Ruby X.Y and then for some reason it didn't.. *sigh*

2025-01-13 11:47 UTC, benjamineskola commented on grover.gemspec
> +  spec.required_ruby_version = ['>= 3.0.0', '< 3.5.0']
@abrom I get where you're coming from, but most gems don't seem to include a maximum supported Ruby version in their gemfiles from what I can tell, and for the most part this doesn't seem to lead to any problems. Is there a particular concern that grover is likely to break on new versions?

(Grover isn't the only one — I think I noticed nokogiri did too. But they released a new version the same day. I'm absolutely not going to suggest that you should be expected to release new versions on Christmas Day; but I do wonder if removing the upper bound would lead to any actual problems.)

2025-01-13 11:52 UTC, merged

2025-01-13 11:56 UTC, abrom commented
Thanks @murajun1978 👍 Released in [v1.2.2](https://rubygems.org/gems/grover/versions/1.2.2)

2025-01-13 13:07 UTC, abrom commented on grover.gemspec
> +  spec.required_ruby_version = ['>= 3.0.0', '< 3.5.0']
![image](https://github.com/user-attachments/assets/47dd722f-baf4-4705-b79b-26139bc8e963)

😉

2025-01-13 15:33 UTC, pboling commented
> Each release runs through a CI suite to ensure the gem is going to behave exactly how it is supposed to. How would that work for a yet to be released language?

I can only tell you how I do it for the dozens of gems I maintain, and that is: I run the CI against `ruby-head`, which is the next Ruby release.